# build, test, and ftp deploy a jekyll site
name: ci:deploy
on:
  push:
    branches:
      - main
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    - name: 📂 Change Directory
      run: |
        cd ..
        cd new_students_warsh_app
        
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server-dir: home/reports/new_students_warsh_app/
        server: reports.furqangroup.com
        username: hatim@reports.furqangroup.com
        password: ${{ secrets.FTP_PASSWORD }}
