# build, test, and ftp deploy a jekyll site
name: ci:deploy
on:
  push:
    branches:
      - main
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    - name: 📂 Change Directory
      run: |
        cd ..
        pwd
        echo 123
        
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server-dir: public_html/test/
        server: reports.furqangroup.com
        username: HatemFurqan@reports.furqangroup.com
        password: ${{ secrets.FTP_PASSWORD }}
